run:
  tests: true
  timeout: 5m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs-use-default: true

linters-settings:
  goimports:
    local-prefixes: antrea.io/libOpenflow

linters:
  disable-all: true
  enable: # see https://golangci-lint.run/usage/linters/
    - deadcode
    - staticcheck
    - govet
    - gofmt
    - goimports
    - gosec
    - misspell

run:
  deadline: 5m
